In [1]:
import pandas as pd
import numpy as np
import plotly.express as px
import pickle
import os

In [2]:
dir_path=os.getcwd()
dir_path

'/Users/payalparida/Documents/Python activity/VS Code/Git Repository/Global_CO2_Emissions_Dashboard_1960-2018'

In [3]:
for file in os.listdir(dir_path):
    if file.endswith('.csv'):
        file_path=os.path.join(dir_path,file)
print(file_path)

/Users/payalparida/Documents/Python activity/VS Code/Git Repository/Global_CO2_Emissions_Dashboard_1960-2018/CO2_Emissions_1960-2018.csv

In [5]:
df=pd.read_csv(file_path,index_col='Country Name')
df.head()

,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,...,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
Country Name,,,,,,,,,,,,,,,,,,,,,
Aruba,204.631696,208.837879,226.081890,214.785217,207.626699,185.213644,172.158729,210.819017,194.917536,253.544574,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Africa Eastern and Southern,0.906060,0.922474,0.930816,0.940570,0.996033,1.047280,1.033908,1.052204,1.079727,1.104632,...,1.021954,1.048876,1.005338,1.021646,1.031833,1.041145,0.987393,0.971016,0.959978,0.933541
Afghanistan,0.046057,0.053589,0.073721,0.074161,0.086174,0.101285,0.107399,0.123409,0.115142,0.086510,...,0.211306,0.297065,0.407074,0.335351,0.263716,0.234037,0.232176,0.208857,0.203328,0.200151
Africa Western and Central,0.090880,0.095283,0.096612,0.112376,0.133258,0.184803,0.193676,0.189305,0.143989,0.202129,...,0.426770,0.472819,0.497023,0.490867,0.504655,0.507671,0.480743,0.472959,0.476438,0.515544
Angola,0.100835,0.082204,0.210533,0.202739,0.213562,0.205891,0.268937,0.172096,0.289702,0.480199,...,1.205902,1.221515,1.216317,1.204799,1.261542,1.285365,1.260921,1.227703,1.034317,0.887380

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 266 entries, Aruba to Zimbabwe
Data columns (total 59 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   1960    203 non-null    float64
 1   1961    204 non-null    float64
 2   1962    206 non-null    float64
 3   1963    207 non-null    float64
 4   1964    213 non-null    float64
 5   1965    213 non-null    float64
 6   1966    213 non-null    float64
 7   1967    213 non-null    float64
 8   1968    213 non-null    float64
 9   1969    213 non-null    float64
 10  1970    214 non-null    float64
 11  1971    215 non-null    float64
 12  1972    216 non-null    float64
 13  1973    216 non-null    float64
 14  1974    216 non-null    float64
 15  1975    216 non-null    float64
 16  1976    216 non-null    float64
 17  1977    216 non-null    float64
 18  1978    216 non-null    float64
 19  1979    216 non-null    float64
 20  1980    216 non-null    float64
 21  1981    216 non-null    float64
 22  1982    216 non-null    float64
 23  1983    216 non-null    float64
 24  1984    216 non-null    float64
 25  1985    216 non-null    float64
 26  1986    216 non-null    float64
 27  1987    216 non-null    float64
 28  1988    216 non-null    float64
 29  1989    216 non-null    float64
 30  1990    238 non-null    float64
 31  1991    239 non-null    float64
 32  1992    238 non-null    float64
 33  1993    238 non-null    float64
 34  1994    238 non-null    float64
 35  1995    239 non-null    float64
 36  1996    239 non-null    float64
 37  1997    239 non-null    float64
 38  1998    239 non-null    float64
 39  1999    239 non-null    float64
 40  2000    239 non-null    float64
 41  2001    239 non-null    float64
 42  2002    239 non-null    float64
 43  2003    239 non-null    float64
 44  2004    239 non-null    float64
 45  2005    239 non-null    float64
 46  2006    239 non-null    float64
 47  2007    239 non-null    float64
 48  2008    239 non-null    float64
 49  2009    239 non-null    float64
 50  2010    239 non-null    float64
 51  2011    239 non-null    float64
 52  2012    239 non-null    float64
 53  2013    239 non-null    float64
 54  2014    239 non-null    float64
 55  2015    239 non-null    float64
 56  2016    239 non-null    float64
 57  2017    239 non-null    float64
 58  2018    239 non-null    float64
dtypes: float64(59)
memory usage: 124.7+ KB

In [7]:
df1=df.transpose()
df1.index=pd.to_datetime(df1.index).year
df1.head()

Country Name,Aruba,Africa Eastern and Southern,Afghanistan,Africa Western and Central,Angola,Albania,Andorra,Arab World,United Arab Emirates,Argentina,...,Virgin Islands (U.S.),Vietnam,Vanuatu,World,Samoa,Kosovo,"Yemen, Rep.",South Africa,Zambia,Zimbabwe
1960,204.631696,0.906060,0.046057,0.090880,0.100835,1.258195,NaN,0.609268,0.119037,2.383343,...,NaN,0.181947,NaN,3.121158,0.135031,NaN,0.011038,5.727223,NaN,NaN
1961,208.837879,0.922474,0.053589,0.095283,0.082204,1.374186,NaN,0.662618,0.109136,2.458551,...,NaN,0.183099,NaN,3.068090,0.163542,NaN,0.013599,5.832621,NaN,NaN
1962,226.081890,0.930816,0.073721,0.096612,0.210533,1.439956,NaN,0.727117,0.163542,2.538447,...,NaN,0.217694,0.595002,3.114839,0.158377,NaN,0.012729,5.887168,NaN,NaN
1963,214.785217,0.940570,0.074161,0.112376,0.202739,1.181681,NaN,0.853116,0.175833,2.330685,...,NaN,0.196997,0.471849,3.221195,0.184037,NaN,0.014518,5.961337,NaN,NaN
1964,207.626699,0.996033,0.086174,0.133258,0.213562,1.111742,NaN,0.972381,0.132815,2.553442,...,NaN,0.209870,0.864427,3.324046,0.208106,NaN,0.017550,6.332343,0.946606,1.034904

In [8]:
fig_1=px.line(data_frame=df1, x=df1.index, y='World', markers=True)
fig_1

In [9]:
with open('line_chart.pkl','wb') as file:
    pickle.dump(fig_1,file)

In [10]:
df.head()

,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,...,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
Country Name,,,,,,,,,,,,,,,,,,,,,
Aruba,204.631696,208.837879,226.081890,214.785217,207.626699,185.213644,172.158729,210.819017,194.917536,253.544574,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Africa Eastern and Southern,0.906060,0.922474,0.930816,0.940570,0.996033,1.047280,1.033908,1.052204,1.079727,1.104632,...,1.021954,1.048876,1.005338,1.021646,1.031833,1.041145,0.987393,0.971016,0.959978,0.933541
Afghanistan,0.046057,0.053589,0.073721,0.074161,0.086174,0.101285,0.107399,0.123409,0.115142,0.086510,...,0.211306,0.297065,0.407074,0.335351,0.263716,0.234037,0.232176,0.208857,0.203328,0.200151
Africa Western and Central,0.090880,0.095283,0.096612,0.112376,0.133258,0.184803,0.193676,0.189305,0.143989,0.202129,...,0.426770,0.472819,0.497023,0.490867,0.504655,0.507671,0.480743,0.472959,0.476438,0.515544
Angola,0.100835,0.082204,0.210533,0.202739,0.213562,0.205891,0.268937,0.172096,0.289702,0.480199,...,1.205902,1.221515,1.216317,1.204799,1.261542,1.285365,1.260921,1.227703,1.034317,0.887380

In [11]:
df.reset_index(level=0,inplace=True)
df.head()

,Country Name,1960,1961,1962,1963,1964,1965,1966,1967,1968,...,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
0,Aruba,204.631696,208.837879,226.081890,214.785217,207.626699,185.213644,172.158729,210.819017,194.917536,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Africa Eastern and Southern,0.906060,0.922474,0.930816,0.940570,0.996033,1.047280,1.033908,1.052204,1.079727,...,1.021954,1.048876,1.005338,1.021646,1.031833,1.041145,0.987393,0.971016,0.959978,0.933541
2,Afghanistan,0.046057,0.053589,0.073721,0.074161,0.086174,0.101285,0.107399,0.123409,0.115142,...,0.211306,0.297065,0.407074,0.335351,0.263716,0.234037,0.232176,0.208857,0.203328,0.200151
3,Africa Western and Central,0.090880,0.095283,0.096612,0.112376,0.133258,0.184803,0.193676,0.189305,0.143989,...,0.426770,0.472819,0.497023,0.490867,0.504655,0.507671,0.480743,0.472959,0.476438,0.515544
4,Angola,0.100835,0.082204,0.210533,0.202739,0.213562,0.205891,0.268937,0.172096,0.289702,...,1.205902,1.221515,1.216317,1.204799,1.261542,1.285365,1.260921,1.227703,1.034317,0.887380

In [14]:
df2=df.melt(id_vars='Country Name',var_name='Year').sort_values(by=['Country Name'])
df2.head()

      Country Name  Year     value
11174  Afghanistan  2002  0.048671
9844   Afghanistan  1997  0.056827
3992   Afghanistan  1975  0.167612
10642  Afghanistan  2000  0.037055
15430  Afghanistan  2018  0.200151

In [15]:
fig_2=px.choropleth(data_frame=df2[df2['Country Name']!='World'],locationmode='country names',
                    locations='Country Name', color='value', animation_frame='Year',
                    color_continuous_scale=px.colors.sequential.RdBu_r, range_color=(200,0))
fig_2

/var/folders/24/9nbv03mn2tn5jqnf3863cpjm0000gn/T/ipykernel_10676/1246843699.py:1: DeprecationWarning: The library used by the *country names* `locationmode` option is changing in an upcoming version. Country names in existing plots may not work in the new version. To ensure consistent behavior, consider setting `locationmode` to *ISO-3*.
  fig_2=px.choropleth(data_frame=df2[df2['Country Name']!='World'],locationmode='country names',

In [16]:
with open('map_chart.pkl','wb') as file:
    pickle.dump(fig_2,file)

In [ ]:
from raceplotly.plots import barplot
race_plot=barplot(df=df2[df2['Country Name']!='World'],item_column='Country Name', value_column='value',time_column='Year', top_entries=10)
fig_3=race_plot.plot(value_label='Value',item_label='Top 10 Countries')
fig_3

/Users/payalparida/Documents/Python activity/VS Code/Git Repository/Global_CO2_Emissions_Dashboard_1960-2018/co2env/lib/python3.10/site-packages/raceplotly/plots.py:295: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.df['color'] = self.df[self.item_column].map(colors)

In [21]:
with open('bar_chart.pkl','wb') as file:
    pickle.dump(fig_3,file)